"""add_super_admin_role_and_soft_delete

Revision ID: 39ac1e823fed
Revises: 8cd821e5f04a
Create Date: 2026-05-31 18:30:45.348415

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39ac1e823fed"
down_revision: str | None = "8cd821e5f04a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE user_role ADD VALUE 'super_admin'")
    op.execute("ALTER TYPE user_role ADD VALUE 'SUPER_ADMIN'")
    op.add_column("businesses", sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False))
    op.add_column("businesses", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_at")
    op.drop_column("businesses", "deleted_at")
    op.drop_column("businesses", "is_active")
    # ### end Alembic commands ###
