"""create_workflows_tables

Revision ID: 8cd821e5f04a
Revises: 3a528661ceea
Create Date: 2026-05-28 02:20:24.721477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cd821e5f04a'
down_revision: Union[str, None] = '3a528661ceea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('log_depth', sa.String(length=20), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_lookup', 'workflows', ['business_id', 'trigger_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_workflows_business_id'), 'workflows', ['business_id'], unique=False)
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_table('workflow_execution_logs',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_execution_logs_business_id'), 'workflow_execution_logs', ['business_id'], unique=False)
    op.create_index(op.f('ix_workflow_execution_logs_id'), 'workflow_execution_logs', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_execution_logs_workflow_id'), 'workflow_execution_logs', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_execution_logs_workflow_id'), table_name='workflow_execution_logs')
    op.drop_index(op.f('ix_workflow_execution_logs_id'), table_name='workflow_execution_logs')
    op.drop_index(op.f('ix_workflow_execution_logs_business_id'), table_name='workflow_execution_logs')
    op.drop_table('workflow_execution_logs')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_business_id'), table_name='workflows')
    op.drop_index('ix_workflow_lookup', table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
